baseURL = "https://dyekuu.github.io/"
languageCode = "en-us"
title = "Kunhao Zheng"
theme = "archie"
copyright = "© Kunhao Zheng"
googleAnalytics = "G-7RPL6R7B6N"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=1 # articles per page

enableEmoji = true # https://www.webfx.com/tools/emoji-cheat-sheet/

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	# comments=true
	subtitle = """![](/images/kunhao.jpeg)  
	Hi, I'm Kunhao Zheng (pronunced like `cun-how`), a passionate learner, as well as a student researcher, in machine/deep learning. \
	I tend to devote myself to projects that are meaningful and do good to the community.  
	\\
	Feel free to look around. If you want to contact me, drop me a message on `dyekuu [at] gmail [dot] com`."""

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/DyeKuu/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/KunhaoZ/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/kunhao-zheng-x18/"

[[params.social]]
name = "Google Scholar"
icon = "google-scholar"
url = "https://scholar.google.com/citations?user=zDy4jSYAAAAJ&hl=en"

[[params.social]]
name = "DBLP"
icon = "dblp"
url = "https://scholar.google.com/citations?user=zDy4jSYAAAAJ&hl=en"
# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About Me"
url = "/about/about-me"
weight = 2

[[menu.main]]
name = "Research"
url = "/research/overview"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3


# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 4
